name: Supabase Keep Alive

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Send a request to Supabase
              run: |
                  curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/radios?select=*" \
                  -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
                  -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
